name: orthoidp
dependencies:
  - sys
  - os
  - jupyter
  - json
  - requests
  - io
  - datetime
  - random
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - biopython
  - scikit-learn
  - pip
  - pip:
    - localcider
    - mdtraj
