name: orthoidp
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - tk
  - jupyter_client
  - appnope
  - backports
  - decorator
  - importlib-metadata
  - packaging
  - typing-extensions
  - zipp
  - ipykernel
  - ca-certificates
  - parso
  - psutil
  - debugpy
  - stack_data
  - wcwidth
  - pytest
  - executing
  - python=3.10
  - pandas
  - matplotlib-inline
  - platformdirs
  - ptyprocess
  - pure_eval
  - backports.functools_lru_cache
  - libzlib
  - bzip2
  - pexpect
  - wheel
  - libsqlite
  - pygments
  - libsodium
  - pickleshare
  - ncurses
  - nest-asyncio
  - zeromq
  - ipython
  - jedi
  - prompt-toolkit
  - seaborn
  - importlib_metadata
  - pyzmq
  - libffi
  - backcall
  - openssl
  - openmm
  - readline
  - setuptools
  - matplotlib
  - jupyter_core
  - asttokens
  - six
  - traitlets
  - typing_extensions
  - xz
  - tqdm
  - comm
  - libcxx
  - tornado
  - python-dateutil
  - python_abi
  - tzdata
  - biopython
  - pip
  - scikit-learn