name: orthoidp
channels:
  - defaults
dependencies:
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - biopython
  - scikit-learn
  - tzdata
  - ncurses
  - libsqlite
  - python=3.10
  - traitlets
  - backports
  - pygments
  - ptyprocess
  - appnope
  - matplotlib-inline
  - tk
  - parso
  - zeromq
  - comm
  - prompt-toolkit
  - python_abi
  - bzip2
  - ipython
  - python-dateutil
  - pure_eval
  - setuptools
  - importlib-metadata
  - ca-certificates
  - zipp
  - openssl
  - libzlib
  - wheel
  - stack_data
  - pickleshare
  - asttokens
  - six
  - libsodium
  - packaging
  - jedi
  - wcwidth
  - executing
  - typing-extensions
  - importlib_metadata
  - platformdirs
  - tornado
  - libffi
  - pip
  - pexpect
  - nest-asyncio
  - jupyter_core
  - debugpy
  - typing_extensions
  - libcxx
  - jupyter_client
  - backports.functools_lru_cache
  - readline
  - pyzmq
  - xz
  - backcall
  - psutil
  - decorator
  - ipykernel
  - openmm
  - pytest
